Update app and runtime
flathub/org.gnome.gbrainy pull request #9
Opened 2022-07-18 13:49 UTC by wjt

Fixes #6 inasmuch as it builds.
Fixes #7 except a newer runtime.

2022-07-18 14:18 UTC, hfiguiere requested changes

2022-07-18 14:18 UTC, hfiguiere commented on org.gnome.gbrainy.json
> +    "runtime-version": "41",
`42` is the latest.

2022-07-18 14:18 UTC, hfiguiere commented on org.gnome.gbrainy.json
> +            "config-opts": [],
you could as well remove it.

```suggestion
```

2022-07-18 14:18 UTC, hfiguiere commented on org.gnome.gbrainy.json
> +            "PKG_CONFIG_PATH": "/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/sdk/mono6/lib/pkgconfig"
`"append-pkg-config-path": "/usr/lib/sdk/mono6/lib/pkgconfig"` is probably better here.

2022-07-18 14:19 UTC, hfiguiere commented on org.gnome.gbrainy.json
> +            "PKG_CONFIG_PATH": "/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/sdk/mono6/lib/pkgconfig"
just to clarify it would be one level up out of the `env` object.

2022-07-18 21:25 UTC, wjt commented on org.gnome.gbrainy.json
> +    "runtime-version": "41",
Good catcH!

2022-07-18 21:27 UTC, wjt commented
Cracked it!

2022-07-19 06:09 UTC, wjt commented
Test build works on my machine™

2022-07-20 20:34 UTC, jordimas commented
Thanks, really appreciated

2022-07-20 20:35 UTC, merged